# Generated by Django 5.0.7 on 2024-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='complaint',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
